version: "2.4"

services:
  demo:
    container_name: ${COMPOSE_PROJECT_NAME}_demo
    image: bitcoinstack/relay:${RELAY_VERSION}
    restart: unless-stopped
    command: ['node', 'subscriber.js']
    depends_on:
      - bitcoin
      - alice
    environment:
      - BITCOIN_HOST
      - BITCOIN_RPC_PORT
      - BITCOIN_RPC_USER
      - BITCOIN_RPC_PASSWORD
      - ALICE_HOST
      - ALICE_RPC_PORT
    volumes:
      - ./relay/app:/usr/src/app
      - alice_data:/lnd:ro
    networks:
      - bitcoinstacknet

  electrs:
    container_name: ${COMPOSE_PROJECT_NAME}_electrs
    image: bitcoinstack/electrs:${ELECTRS_VERSION}-alpine
    restart: unless-stopped
    command: [
      'electrs',
      '--timestamp',
      '--network=regtest',
      '--daemon-p2p-addr=bitcoin:${BITCOIN_PORT}',
      '--daemon-rpc-addr=bitcoin:${BITCOIN_RPC_PORT}',
      '--electrum-rpc-addr=0.0.0.0:${ELECTRS_PORT}',
      '--db-dir=/home/electrs/db',
      '--log-filters=INFO'
    ]
    ports:
      - "127.0.0.1:${ELECTRS_PORT}:${ELECTRS_PORT}"
    depends_on:
      - bitcoin
    networks:
      - bitcoinstacknet

  rtl:
    container_name: ${COMPOSE_PROJECT_NAME}_rtl
    image: shahanafarooqui/rtl:${RTL_VERSION}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${RTL_PORT}:${RTL_PORT}"
    depends_on:
      - alice
      - bob
    environment:
      - PORT=${RTL_PORT}
      - HOST=${RTL_HOST}
      - RTL_CONFIG_PATH=/RTL/config
    volumes:
      - ./rtl:/RTL/config
      - alice_data:/alice:ro
      - bob_data:/bob:ro
    networks:
      - bitcoinstacknet