name: Testing Stack

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  test-bitcoind:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Run Stack
        run: docker compose up -d bitcoin electrs
      - name: Boostrap Bitcoind
        run: |
          bin/stack bitcoin -named createwallet wallet_name=default descriptors=false
          bin/stack bitcoin sethdseed true cSXteaZPxiDNEjtsgMhDKik5CL6YUc2hrEdkm51DrL85873UUFiQ
          bin/stack bitcoin generate 101
      - name: Query Bitcoind
        run: curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getwalletinfo","params":[]}' -H 'content-type:text/plain;' http://bitcoin:bitcoin@127.0.0.1:18889
      - name: Query Electrs
        run: |
          echo '{"jsonrpc":"2.0","method":"blockchain.block.header","id":"curltext","params":[0]}' | nc 127.0.0.1 50001 -w3
          echo '{"jsonrpc":"2.0","method":"blockchain.block.header","id":"curltext","params":[101]}' | nc 127.0.0.1 50001 -w3